//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foadcours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eleve
    {
        public int IdEleve { get; set; }
        public string NomPrenomEleve { get; set; }
        public string EmailEleve { get; set; }
        public string AdresseEleve { get; set; }
        public Nullable<int> IdService { get; set; }
    }
}
